interface Country {
  value: string;
  label: {
    en: string;
    es: string;
  };
}

export const countries: Country[] = [
  { value: "Afghanistan", label: { en: "Afghanistan", es: "Afganistán" } },
  { value: "Albania", label: { en: "Albania", es: "Albania" } },
  { value: "Algeria", label: { en: "Algeria", es: "Argelia" } },
  { value: "Andorra", label: { en: "Andorra", es: "Andorra" } },
  { value: "Angola", label: { en: "Angola", es: "Angola" } },
  { value: "Antigua and Barbuda", label: { en: "Antigua and Barbuda", es: "Antigua y Barbuda" } },
  { value: "Argentina", label: { en: "Argentina", es: "Argentina" } },
  { value: "Armenia", label: { en: "Armenia", es: "Armenia" } },
  { value: "Australia", label: { en: "Australia", es: "Australia" } },
  { value: "Austria", label: { en: "Austria", es: "Austria" } },
  { value: "Azerbaijan", label: { en: "Azerbaijan", es: "Azerbaiyán" } },
  { value: "Bahamas", label: { en: "Bahamas", es: "Bahamas" } },
  { value: "Bahrain", label: { en: "Bahrain", es: "Baréin" } },
  { value: "Bangladesh", label: { en: "Bangladesh", es: "Bangladés" } },
  { value: "Barbados", label: { en: "Barbados", es: "Barbados" } },
  { value: "Belarus", label: { en: "Belarus", es: "Bielorrusia" } },
  { value: "Belgium", label: { en: "Belgium", es: "Bélgica" } },
  { value: "Belize", label: { en: "Belize", es: "Belice" } },
  { value: "Benin", label: { en: "Benin", es: "Benín" } },
  { value: "Bhutan", label: { en: "Bhutan", es: "Bután" } },
  { value: "Bolivia", label: { en: "Bolivia", es: "Bolivia" } },
  { value: "Bosnia and Herzegovina", label: { en: "Bosnia and Herzegovina", es: "Bosnia y Herzegovina" } },
  { value: "Botswana", label: { en: "Botswana", es: "Botsuana" } },
  { value: "Brazil", label: { en: "Brazil", es: "Brasil" } },
  { value: "Brunei", label: { en: "Brunei", es: "Brunéi" } },
  { value: "Bulgaria", label: { en: "Bulgaria", es: "Bulgaria" } },
  { value: "Burkina Faso", label: { en: "Burkina Faso", es: "Burkina Faso" } },
  { value: "Burundi", label: { en: "Burundi", es: "Burundi" } },
  { value: "Cabo Verde", label: { en: "Cabo Verde", es: "Cabo Verde" } },
  { value: "Cambodia", label: { en: "Cambodia", es: "Camboya" } },
  { value: "Cameroon", label: { en: "Cameroon", es: "Camerún" } },
  { value: "Canada", label: { en: "Canada", es: "Canadá" } },
  { value: "Central African Republic", label: { en: "Central African Republic", es: "República Centroafricana" } },
  { value: "Chad", label: { en: "Chad", es: "Chad" } },
  { value: "Chile", label: { en: "Chile", es: "Chile" } },
  { value: "China", label: { en: "China", es: "China" } },
  { value: "Colombia", label: { en: "Colombia", es: "Colombia" } },
  { value: "Comoros", label: { en: "Comoros", es: "Comoras" } },
  { value: "Congo, Democratic Republic of the", label: { en: "Congo, Democratic Republic of the", es: "Congo, República Democrática del" } },
  { value: "Congo, Republic of the", label: { en: "Congo, Republic of the", es: "Congo, República del" } },
  { value: "Costa Rica", label: { en: "Costa Rica", es: "Costa Rica" } },
  { value: "Cote d'Ivoire", label: { en: "Cote d'Ivoire", es: "Costa de Marfil" } },
  { value: "Croatia", label: { en: "Croatia", es: "Croacia" } },
  { value: "Cuba", label: { en: "Cuba", es: "Cuba" } },
  { value: "Cyprus", label: { en: "Cyprus", es: "Chipre" } },
  { value: "Czechia", label: { en: "Czechia", es: "Chequia" } },
  { value: "Denmark", label: { en: "Denmark", es: "Dinamarca" } },
  { value: "Djibouti", label: { en: "Djibouti", es: "Yibuti" } },
  { value: "Dominica", label: { en: "Dominica", es: "Dominica" } },
  { value: "Dominican Republic", label: { en: "Dominican Republic", es: "República Dominicana" } },
  { value: "Ecuador", label: { en: "Ecuador", es: "Ecuador" } },
  { value: "Egypt", label: { en: "Egypt", es: "Egipto" } },
  { value: "El Salvador", label: { en: "El Salvador", es: "El Salvador" } },
  { value: "Equatorial Guinea", label: { en: "Equatorial Guinea", es: "Guinea Ecuatorial" } },
  { value: "Eritrea", label: { en: "Eritrea", es: "Eritrea" } },
  { value: "Estonia", label: { en: "Estonia", es: "Estonia" } },
  { value: "Eswatini", label: { en: "Eswatini", es: "Esuatini" } },
  { value: "Ethiopia", label: { en: "Ethiopia", es: "Etiopía" } },
  { value: "Fiji", label: { en: "Fiji", es: "Fiyi" } },
  { value: "Finland", label: { en: "Finland", es: "Finlandia" } },
  { value: "France", label: { en: "France", es: "Francia" } },
  { value: "Gabon", label: { en: "Gabon", es: "Gabón" } },
  { value: "Gambia", label: { en: "Gambia", es: "Gambia" } },
  { value: "Georgia", label: { en: "Georgia", es: "Georgia" } },
  { value: "Germany", label: { en: "Germany", es: "Alemania" } },
  { value: "Ghana", label: { en: "Ghana", es: "Ghana" } },
  { value: "Greece", label: { en: "Greece", es: "Grecia" } },
  { value: "Grenada", label: { en: "Grenada", es: "Granada" } },
  { value: "Guatemala", label: { en: "Guatemala", es: "Guatemala" } },
  { value: "Guinea", label: { en: "Guinea", es: "Guinea" } },
  { value: "Guinea-Bissau", label: { en: "Guinea-Bissau", es: "Guinea-Bisáu" } },
  { value: "Guyana", label: { en: "Guyana", es: "Guyana" } },
  { value: "Haiti", label: { en: "Haiti", es: "Haití" } },
  { value: "Honduras", label: { en: "Honduras", es: "Honduras" } },
  { value: "Hungary", label: { en: "Hungary", es: "Hungría" } },
  { value: "Iceland", label: { en: "Iceland", es: "Islandia" } },
  { value: "India", label: { en: "India", es: "India" } },
  { value: "Indonesia", label: { en: "Indonesia", es: "Indonesia" } },
  { value: "Iran", label: { en: "Iran", es: "Irán" } },
  { value: "Iraq", label: { en: "Iraq", es: "Irak" } },
  { value: "Ireland", label: { en: "Ireland", es: "Irlanda" } },
  { value: "Israel", label: { en: "Israel", es: "Israel" } },
  { value: "Italy", label: { en: "Italy", es: "Italia" } },
  { value: "Jamaica", label: { en: "Jamaica", es: "Jamaica" } },
  { value: "Japan", label: { en: "Japan", es: "Japón" } },
  { value: "Jordan", label: { en: "Jordan", es: "Jordania" } },
  { value: "Kazakhstan", label: { en: "Kazakhstan", es: "Kazajistán" } },
  { value: "Kenya", label: { en: "Kenya", es: "Kenia" } },
  { value: "Kiribati", label: { en: "Kiribati", es: "Kiribati" } },
  { value: "Kuwait", label: { en: "Kuwait", es: "Kuwait" } },
  { value: "Kyrgyzstan", label: { en: "Kyrgyzstan", es: "Kirguistán" } },
  { value: "Laos", label: { en: "Laos", es: "Laos" } },
  { value: "Latvia", label: { en: "Latvia", es: "Letonia" } },
  { value: "Lebanon", label: { en: "Lebanon", es: "Líbano" } },
  { value: "Lesotho", label: { en: "Lesotho", es: "Lesoto" } },
  { value: "Liberia", label: { en: "Liberia", es: "Liberia" } },
  { value: "Libya", label: { en: "Libya", es: "Libia" } },
  { value: "Liechtenstein", label: { en: "Liechtenstein", es: "Liechtenstein" } },
  { value: "Lithuania", label: { en: "Lithuania", es: "Lituania" } },
  { value: "Luxembourg", label: { en: "Luxembourg", es: "Luxemburgo" } },
  { value: "Madagascar", label: { en: "Madagascar", es: "Madagascar" } },
  { value: "Malawi", label: { en: "Malawi", es: "Malaui" } },
  { value: "Malaysia", label: { en: "Malaysia", es: "Malasia" } },
  { value: "Maldives", label: { en: "Maldives", es: "Maldivas" } },
  { value: "Mali", label: { en: "Mali", es: "Malí" } },
  { value: "Malta", label: { en: "Malta", es: "Malta" } },
  { value: "Marshall Islands", label: { en: "Marshall Islands", es: "Islas Marshall" } },
  { value: "Mauritania", label: { en: "Mauritania", es: "Mauritania" } },
  { value: "Mauritius", label: { en: "Mauritius", es: "Mauricio" } },
  { value: "Mexico", label: { en: "Mexico", es: "México" } },
  { value: "Micronesia", label: { en: "Micronesia", es: "Micronesia" } },
  { value: "Moldova", label: { en: "Moldova", es: "Moldavia" } },
  { value: "Monaco", label: { en: "Monaco", es: "Mónaco" } },
  { value: "Mongolia", label: { en: "Mongolia", es: "Mongolia" } },
  { value: "Montenegro", label: { en: "Montenegro", es: "Montenegro" } },
  { value: "Morocco", label: { en: "Morocco", es: "Marruecos" } },
  { value: "Mozambique", label: { en: "Mozambique", es: "Mozambique" } },
  { value: "Myanmar", label: { en: "Myanmar", es: "Myanmar" } },
  { value: "Namibia", label: { en: "Namibia", es: "Namibia" } },
  { value: "Nauru", label: { en: "Nauru", es: "Nauru" } },
  { value: "Nepal", label: { en: "Nepal", es: "Nepal" } },
  { value: "Netherlands", label: { en: "Netherlands", es: "Países Bajos" } },
  { value: "New Zealand", label: { en: "New Zealand", es: "Nueva Zelanda" } },
  { value: "Nicaragua", label: { en: "Nicaragua", es: "Nicaragua" } },
  { value: "Niger", label: { en: "Niger", es: "Níger" } },
  { value: "Nigeria", label: { en: "Nigeria", es: "Nigeria" } },
  { value: "North Korea", label: { en: "North Korea", es: "Corea del Norte" } },
  { value: "North Macedonia", label: { en: "North Macedonia", es: "Macedonia del Norte" } },
  { value: "Norway", label: { en: "Norway", es: "Noruega" } },
  { value: "Oman", label: { en: "Oman", es: "Omán" } },
  { value: "Pakistan", label: { en: "Pakistan", es: "Pakistán" } },
  { value: "Palau", label: { en: "Palau", es: "Palaos" } },
  { value: "Palestine State", label: { en: "Palestine State", es: "Estado de Palestina" } },
  { value: "Panama", label: { en: "Panama", es: "Panamá" } },
  { value: "Papua New Guinea", label: { en: "Papua New Guinea", es: "Papúa Nueva Guinea" } },
  { value: "Paraguay", label: { en: "Paraguay", es: "Paraguay" } },
  { value: "Peru", label: { en: "Peru", es: "Perú" } },
  { value: "Philippines", label: { en: "Philippines", es: "Filipinas" } },
  { value: "Poland", label: { en: "Poland", es: "Polonia" } },
  { value: "Portugal", label: { en: "Portugal", es: "Portugal" } },
  { value: "Qatar", label: { en: "Qatar", es: "Catar" } },
  { value: "Romania", label: { en: "Romania", es: "Rumania" } },
  { value: "Russia", label: { en: "Russia", es: "Rusia" } },
  { value: "Rwanda", label: { en: "Rwanda", es: "Ruanda" } },
  { value: "Saint Kitts and Nevis", label: { en: "Saint Kitts and Nevis", es: "San Cristóbal y Nieves" } },
  { value: "Saint Lucia", label: { en: "Saint Lucia", es: "Santa Lucía" } },
  { value: "Saint Vincent and the Grenadines", label: { en: "Saint Vincent and the Grenadines", es: "San Vicente y las Granadinas" } },
  { value: "Samoa", label: { en: "Samoa", es: "Samoa" } },
  { value: "San Marino", label: { en: "San Marino", es: "San Marino" } },
  { value: "Sao Tome and Principe", label: { en: "Sao Tome and Principe", es: "Santo Tomé y Príncipe" } },
  { value: "Saudi Arabia", label: { en: "Saudi Arabia", es: "Arabia Saudita" } },
  { value: "Senegal", label: { en: "Senegal", es: "Senegal" } },
  { value: "Serbia", label: { en: "Serbia", es: "Serbia" } },
  { value: "Seychelles", label: { en: "Seychelles", es: "Seychelles" } },
  { value: "Sierra Leone", label: { en: "Sierra Leone", es: "Sierra Leona" } },
  { value: "Singapore", label: { en: "Singapore", es: "Singapur" } },
  { value: "Slovakia", label: { en: "Slovakia", es: "Eslovaquia" } },
  { value: "Slovenia", label: { en: "Slovenia", es: "Eslovenia" } },
  { value: "Solomon Islands", label: { en: "Solomon Islands", es: "Islas Salomón" } },
  { value: "Somalia", label: { en: "Somalia", es: "Somalia" } },
  { value: "South Africa", label: { en: "South Africa", es: "Sudáfrica" } },
  { value: "South Korea", label: { en: "South Korea", es: "Corea del Sur" } },
  { value: "South Sudan", label: { en: "South Sudan", es: "Sudán del Sur" } },
  { value: "Spain", label: { en: "Spain", es: "España" } },
  { value: "Sri Lanka", label: { en: "Sri Lanka", es: "Sri Lanka" } },
  { value: "Sudan", label: { en: "Sudan", es: "Sudán" } },
  { value: "Suriname", label: { en: "Suriname", es: "Surinam" } },
  { value: "Sweden", label: { en: "Sweden", es: "Suecia" } },
  { value: "Switzerland", label: { en: "Switzerland", es: "Suiza" } },
  { value: "Syria", label: { en: "Syria", es: "Siria" } },
  { value: "Taiwan", label: { en: "Taiwan", es: "Taiwán" } },
  { value: "Tajikistan", label: { en: "Tajikistan", es: "Tayikistán" } },
  { value: "Tanzania", label: { en: "Tanzania", es: "Tanzania" } },
  { value: "Thailand", label: { en: "Thailand", es: "Tailandia" } },
  { value: "Timor-Leste", label: { en: "Timor-Leste", es: "Timor Oriental" } },
  { value: "Togo", label: { en: "Togo", es: "Togo" } },
  { value: "Tonga", label: { en: "Tonga", es: "Tonga" } },
  { value: "Trinidad and Tobago", label: { en: "Trinidad and Tobago", es: "Trinidad y Tobago" } },
  { value: "Tunisia", label: { en: "Tunisia", es: "Túnez" } },
  { value: "Turkey", label: { en: "Turkey", es: "Turquía" } },
  { value: "Turkmenistan", label: { en: "Turkmenistan", es: "Turkmenistán" } },
  { value: "Tuvalu", label: { en: "Tuvalu", es: "Tuvalu" } },
  { value: "Uganda", label: { en: "Uganda", es: "Uganda" } },
  { value: "Ukraine", label: { en: "Ukraine", es: "Ucrania" } },
  { value: "United Arab Emirates", label: { en: "United Arab Emirates", es: "Emiratos Árabes Unidos" } },
  { value: "United Kingdom", label: { en: "United Kingdom", es: "Reino Unido" } },
  { value: "United States", label: { en: "United States", es: "Estados Unidos" } },
  { value: "Uruguay", label: { en: "Uruguay", es: "Uruguay" } },
  { value: "Uzbekistan", label: { en: "Uzbekistan", es: "Uzbekistán" } },
  { value: "Vanuatu", label: { en: "Vanuatu", es: "Vanuatu" } },
  { value: "Vatican City", label: { en: "Vatican City", es: "Ciudad del Vaticano" } },
  { value: "Venezuela", label: { en: "Venezuela", es: "Venezuela" } },
  { value: "Vietnam", label: { en: "Vietnam", es: "Vietnam" } },
  { value: "Yemen", label: { en: "Yemen", es: "Yemen" } },
  { value: "Zambia", label: { en: "Zambia", es: "Zambia" } },
  { value: "Zimbabwe", label: { en: "Zimbabwe", es: "Zimbabue" } }
];
